services:
  keycloak:
    container_name: keycloak_demo
    image: quay.io/keycloak/keycloak:25.0.5
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    volumes:
      - D:/Learning/Spring Boot/data_volumes/keycloak:/opt/keycloak/data
    command:
      - 'start-dev'

  postgres_db:
    container_name: postgres
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: subshub
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - D:/Learning/Spring Boot/data_volumes/postgres:/var/lib/postgresql/data